# Generated by Django 3.2.4 on 2021-06-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210607_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='name',
            new_name='username',
        ),
    ]
