# Generated by Django 3.2.4 on 2021-07-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_invitations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitations',
        ),
    ]
