# Generated by Django 3.2.4 on 2021-06-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rename_name_lead_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.JSONField(null=True),
        ),
    ]
