# Generated by Django 3.2.4 on 2021-06-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='message',
            new_name='apikey',
        ),
    ]
