# Generated by Django 3.2.4 on 2021-07-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_delete_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('sent', 'sent'), ('expired', 'expired')], max_length=30)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
