# Generated by Django 3.2.4 on 2021-07-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='fin_advisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.lead'),
            preserve_default=False,
        ),
    ]
