# Generated by Django 3.2.4 on 2021-06-07 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_rename_message_lead_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fin_advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
