# Generated by Django 3.2.4 on 2021-07-15 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_invitations_fin_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='fin_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='invitations',
            unique_together={('email', 'fin_advisor')},
        ),
    ]
