# Generated by Django 3.2.4 on 2021-06-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_fin_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='password',
            field=models.CharField(default='pass', max_length=140),
        ),
    ]
