# Generated by Django 3.2.4 on 2021-06-08 09:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lead',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
