# Generated by Django 3.2.4 on 2021-06-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_lead_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lead',
            managers=[
            ],
        ),
    ]
