# Generated by Django 3.2.4 on 2021-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_lead_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='password',
            field=models.CharField(max_length=140),
        ),
    ]
