# Generated by Django 3.2.4 on 2021-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_lead_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lead',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='apikey',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
