# Generated by Django 3.2.4 on 2021-06-14 07:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20210609_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('apikey', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.instrument')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.portfolio'),
        ),
    ]
