# Generated by Django 3.2.4 on 2021-06-14 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20210614_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.portfolio'),
        ),
    ]
