# Generated by Django 3.2.4 on 2021-06-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_lead_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
            preserve_default=False,
        ),
    ]
