version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/daniil_project
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: bash -c "celery -A learning_project worker -l info"
    volumes:
      - .:/daniil_project
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    build:
      context: .
    container_name: celery-beat
    command: celery -A learning_project beat -l info
    volumes:
      - .:/daniil_project
    links:
      - celery
      - redis
    depends_on:
      - celery
  cache:
   image: memcached
   ports:
     - "11211:11211"
   entrypoint:
    - memcached
    - -m 64